/* Generated by the Nim Compiler v1.4.2 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

function main_1901043(event_1901045) {
    var canvas_1901052 = document.getElementById("canvas");
    canvas_1901052.width = 640;
    canvas_1901052.height = 480;
    var ctx_1901053 = canvas_1901052.getContext("2d");
    ctx_1901053.fillStyle = "gray";
    ctx_1901053.fillRect(0, 0, 640, 480);
    ctx_1901053.fillStyle = "blue";
    ctx_1901053.fillRect(295, 0, 50, 50);
    ctx_1901053.fillStyle = "yellow";
    ctx_1901053.fillRect(295, 50, 50, 50);
    ctx_1901053.fillStyle = "red";
    ctx_1901053.fillRect(295, 100, 50, 50);

  
}
window.onload = main_1901043;
