/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI721420783 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI1090519044 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1090519043 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI553648336 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554436 = {size: 0,kind: 32,base: null,node: null,finalizer: null};
var NTI553648147 = {size: 0, kind: 16, base: null, node: null, finalizer: null};
var NTI704643075 = {size: 0,kind: 44,base: null,node: null,finalizer: null};
var NTI704643076 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI704643076 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI704643075, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI704643075, name: "a1", sons: null}]};
NTI704643076.node = NNI704643076;
NTI553648147.base = NTI33554436;
var NNI1090519044 = {kind: 1, offset: "fillStyle", len: 0, typ: NTI33554450, name: "fillStyle", sons: null};
NTI1090519044.node = NNI1090519044;
NTI1090519043.base = NTI1090519044;
var NNI553648336 = {kind: 1, offset: "ctx0", len: 0, typ: NTI1090519043, name: "ctx0", sons: null};
NTI553648336.node = NNI553648336;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI553648336.base = NTI33555167;
var NNI721420783 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI33554435, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI721420783.node = NNI721420783;
var DefaultRandSeed_704643086 = {a0: 7616934476015405061n, a1: 15122295919272093642n};

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557352 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2900(ti_p2))) {
      result_33557352 = src_p1;
      }
      else {
        result_33557352 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557352 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557352 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557352 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557352 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557352, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557352 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557352 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557352 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557352[i] = nimCopy(result_33557352[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557352 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557352 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557352[i] = nimCopy(result_33557352[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557352 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557352 = src_p1;
      break;
    }

  return result_33557352;

}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}
                      var helper_704643119 = new BigUint64Array([13739361407582206667n, 15594563132006766882n]);
if (globalThis.utcInstance_889194209 === undefined) {
  globalThis.utcInstance_889194209 = [null];
}
if (globalThis.localInstance_889194210 === undefined) {
  globalThis.localInstance_889194210 = [null];
}

function isFatPointer__system_u2900(ti_p0) {
  var result_33557334 = false;

  BeforeRet: {
    result_33557334 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557334;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}
var state_704643087 = [nimCopy(null, DefaultRandSeed_704643086, NTI704643076)];

function toFloat__system_u1582(i_p0) {
  var result_33556016 = 0.0;

    result_33556016 = i_p0;

  return result_33556016;

}

function HEX2F__system_u1594(x_p0, y_p1) {
  var result_33556029 = 0.0;

    result_33556029 = (toFloat__system_u1582(x_p0) / toFloat__system_u1582(y_p1));

  return result_33556029;

}

function epochTime__pureZtimes_u4713() {
  var result_889197162 = 0.0;

    result_889197162 = HEX2F__system_u1594(new Date().getTime(), 1000);

  return result_889197162;

}

function rotl__pureZrandom_u24(x_p0, k_p1) {
  var result_704643099 = 0n;

    result_704643099 = (BigInt.asUintN(64, x_p0 << BigInt(k_p1)) | (x_p0 >> BigInt(BigInt.asUintN(64, (64n - k_p1)))));

  return result_704643099;

}

function next__pureZrandom_u36(r_p0) {
  var result_704643110 = 0n;

    var s0_704643111 = r_p0.a0;
    var s1_704643112 = r_p0.a1;
    result_704643110 = BigInt.asUintN(64, (s0_704643111 + s1_704643112));
    s1_704643112 = (s1_704643112 ^ s0_704643111);
    r_p0.a0 = ((rotl__pureZrandom_u24(s0_704643111, 55n) ^ s1_704643112) ^ BigInt.asUintN(64, s1_704643112 << BigInt(14)));
    r_p0.a1 = rotl__pureZrandom_u24(s1_704643112, 36n);

  return result_704643110;

}

function skipRandomNumbers__pureZrandom_u45(s_p0) {
    var s0_704643120 = 0n;
    var s1_704643121 = 0n;
    Label1: {
      var i_704643130 = 0;
      var res_553648409 = 0;
      Label2: {
          Label3: while (true) {
          if (!(res_553648409 <= 1)) break Label3;
            i_704643130 = res_553648409;
            Label4: {
              var b_704643135 = 0;
              var i_553648407 = 0;
              Label5: {
                  Label6: while (true) {
                  if (!(i_553648407 < 64)) break Label6;
                    b_704643135 = i_553648407;
                    if (!(((helper_704643119[i_704643130] & BigInt.asUintN(64, 1n << BigInt(BigInt.asUintN(64, BigInt(b_704643135))))) == 0n))) {
                    s0_704643120 = (s0_704643120 ^ s_p0.a0);
                    s1_704643121 = (s1_704643121 ^ s_p0.a1);
                    }
                    
                    (next__pureZrandom_u36(s_p0));
                    i_553648407 += 1;
                  }
              };
            };
            res_553648409 += 1;
          }
      };
    };
    s_p0.a0 = s0_704643120;
    s_p0.a1 = s1_704643121;

  
}

function initRand__pureZrandom_u250(seed_p0) {
    var Temporary1;

  var result_704643324 = [({a0: 0n, a1: 0n})];

    if (!((seed_p0 == 0n))) {
    Temporary1 = seed_p0;
    }
    else {
    Temporary1 = 2147483647n;
    }
    
    var seed_704643330 = Temporary1;
    result_704643324[0] = nimCopy(result_704643324[0], {a0: BigInt.asUintN(64, (seed_704643330 >> BigInt(16))), a1: BigInt.asUintN(64, (seed_704643330 & 65535n))}, NTI704643076);
    skipRandomNumbers__pureZrandom_u45(result_704643324[0]);
    (next__pureZrandom_u36(result_704643324[0]));

  return result_704643324[0];

}

function initRand__pureZrandom_u292() {
  var result_704643365 = ({a0: 0n, a1: 0n});

    var time_704643366 = (BigInt(Math.trunc((epochTime__pureZtimes_u4713() * 1000.0))) & 2147483647n);
    result_704643365 = nimCopy(result_704643365, initRand__pureZrandom_u250(time_704643366), NTI704643076);

  return result_704643365;

}

function randomize__pureZrandom_u299() {
    state_704643087[0] = nimCopy(state_704643087[0], initRand__pureZrandom_u292(), NTI704643076);

  
}

function rand__pureZrandom_u112(r_p0, max_p1) {
  var result_704643188 = 0n;

  BeforeRet: {
    if ((max_p1 == 0n)) {
    break BeforeRet;
    }
    else {
      var max_704643189 = max_p1;
      if ((max_704643189 == 18446744073709551615n)) {
      result_704643188 = next__pureZrandom_u36(r_p0);
      break BeforeRet;
      }
      
      var iters_704643202 = 0;
      Label1: {
          Label2: while (true) {
          if (!true) break Label2;
            var x_704643203 = next__pureZrandom_u36(r_p0);
            if (((x_704643203 <= BigInt.asUintN(64, (18446744073709551615n - (18446744073709551615n % max_704643189)))) || (20 < iters_704643202))) {
            result_704643188 = (x_704643203 % BigInt.asUintN(64, (max_704643189 + 1n)));
            break BeforeRet;
            }
            else {
            iters_704643202 += 1;
            }
            
          }
      };
    }
    
  };

  return result_704643188;

}

function rand__main_u53(r_p0, x_p1) {
  var result_553648185 = 0;

    result_553648185 = Number(BigInt.asIntN(32, BigInt.asUintN(64, (rand__pureZrandom_u112(r_p0, BigInt.asUintN(64, (BigInt.asUintN(64, BigInt(x_p1.b)) - BigInt.asUintN(64, BigInt(x_p1.a))))) + BigInt.asUintN(64, BigInt(x_p1.a))))));

  return result_553648185;

}

function rand__main_u45(x_p0) {
  var result_553648176 = 0;

    result_553648176 = rand__main_u53(state_704643087[0], x_p0);

  return result_553648176;

}

function HEX2EHEX2E__stdZstrbasics_u48(a_p0, b_p1) {
  var result_989855797 = ({a: 0, b: 0});

    result_989855797 = nimCopy(result_989855797, {a: a_p0, b: b_p1}, NTI721420783);

  return result_989855797;

}

function shuffleBoard__main_u15() {
    Label1: {
      var y_553648148 = 0;
      var res_553648415 = 1;
      Label2: {
          Label3: while (true) {
          if (!(res_553648415 <= 50)) break Label3;
            y_553648148 = res_553648415;
            Label4: {
              var x_553648153 = 0;
              var res_553648413 = 1;
              Label5: {
                  Label6: while (true) {
                  if (!(res_553648413 <= 15)) break Label6;
                    x_553648153 = res_553648413;
                    board_553648141[0][y_553648148][x_553648153] = 1;
                    res_553648413 += 1;
                  }
              };
            };
            res_553648415 += 1;
          }
      };
    };
    Label7: {
      var y_553648158 = 0;
      var res_553648421 = 1;
      Label8: {
          Label9: while (true) {
          if (!(res_553648421 <= 50)) break Label9;
            y_553648158 = res_553648421;
            Label10: {
              var x_553648163 = 0;
              var res_553648419 = 1;
              Label11: {
                  Label12: while (true) {
                  if (!(res_553648419 <= 50)) break Label12;
                    x_553648163 = res_553648419;
                    var randomIndex_553648194 = rand__main_u45(HEX2EHEX2E__stdZstrbasics_u48(1, 50));
                    var tmp_553648195 = board_553648141[0][y_553648158][x_553648163];
                    board_553648141[0][y_553648158][x_553648163] = board_553648141[0][y_553648158][randomIndex_553648194];
                    board_553648141[0][y_553648158][randomIndex_553648194] = tmp_553648195;
                    res_553648419 += 1;
                  }
              };
            };
            res_553648421 += 1;
          }
      };
    };

  
}

function outputBoard__main_u126(ctx_p0) {
    Label1: {
      var y_553648260 = 0;
      var res_553648428 = 1;
      Label2: {
          Label3: while (true) {
          if (!(res_553648428 <= 50)) break Label3;
            y_553648260 = res_553648428;
            Label4: {
              var x_553648265 = 0;
              var res_553648426 = 1;
              Label5: {
                  Label6: while (true) {
                  if (!(res_553648426 <= 50)) break Label6;
                    x_553648265 = res_553648426;
                    if ((board_553648141[0][y_553648260][x_553648265] == 1)) {
                    ctx_p0.fillStyle = "#11d319";
                    ctx_p0.fillRect((5 * (x_553648265 - 1)), (5 * (y_553648260 - 1)), 5, 5);
                    }
                    else {
                      ctx_p0.fillStyle = "black";
                      ctx_p0.fillRect((5 * (x_553648265 - 1)), (5 * (y_553648260 - 1)), 5, 5);
                    }
                    
                    res_553648426 += 1;
                  }
              };
            };
            res_553648428 += 1;
          }
      };
    };

  
}

function countNeighbors__main_u84(y_p0, x_p1) {
    var Temporary1;
    var Temporary2;
    var Temporary3;
    var Temporary4;
    var Temporary5;
    var Temporary6;

  var result_553648215 = 0;

    result_553648215 = ((((((((Temporary1 = board_553648141[0][(y_p0 - 1)], Temporary1)[(x_p1 - 1)] + (Temporary2 = board_553648141[0][(y_p0 - 1)], Temporary2)[x_p1]) + (Temporary3 = board_553648141[0][(y_p0 - 1)], Temporary3)[(x_p1 + 1)]) + board_553648141[0][y_p0][(x_p1 - 1)]) + board_553648141[0][y_p0][(x_p1 + 1)]) + (Temporary4 = board_553648141[0][(y_p0 + 1)], Temporary4)[(x_p1 - 1)]) + (Temporary5 = board_553648141[0][(y_p0 + 1)], Temporary5)[x_p1]) + (Temporary6 = board_553648141[0][(y_p0 + 1)], Temporary6)[(x_p1 + 1)]);

  return result_553648215;

}

function nextGeneration__main_u88() {
    var neighbors_553648217 = arrayConstr(52, new Int8Array(52), NTI553648147);
    Label1: {
      var y_553648222 = 0;
      var res_553648434 = 1;
      Label2: {
          Label3: while (true) {
          if (!(res_553648434 <= 50)) break Label3;
            y_553648222 = res_553648434;
            Label4: {
              var x_553648227 = 0;
              var res_553648432 = 1;
              Label5: {
                  Label6: while (true) {
                  if (!(res_553648432 <= 50)) break Label6;
                    x_553648227 = res_553648432;
                    neighbors_553648217[y_553648222][x_553648227] = countNeighbors__main_u84(y_553648222, x_553648227);
                    res_553648432 += 1;
                  }
              };
            };
            res_553648434 += 1;
          }
      };
    };
    Label7: {
      var y_553648232 = 0;
      var res_553648440 = 1;
      Label8: {
          Label9: while (true) {
          if (!(res_553648440 <= 50)) break Label9;
            y_553648232 = res_553648440;
            Label10: {
              var x_553648237 = 0;
              var res_553648438 = 1;
              Label11: {
                  Label12: while (true) {
                  if (!(res_553648438 <= 50)) break Label12;
                    x_553648237 = res_553648438;
                    if (                    neighbors_553648217[y_553648232][x_553648237] == 2                    ){                      }
                    else if (                    neighbors_553648217[y_553648232][x_553648237] == 3                    ){                      board_553648141[0][y_553648232][x_553648237] = 1;
                      }
                    else{
                      board_553648141[0][y_553648232][x_553648237] = 0;
                      }
                    res_553648438 += 1;
                  }
              };
            };
            res_553648440 += 1;
          }
      };
    };

  
}

function mainloop__main_u142(ctx_p0) {
    nextGeneration__main_u88();
    outputBoard__main_u126(ctx_p0);

  
}

function update__main_u144(timestamp_p0) {
    var Temporary1;
    var Temporary2;

  BeforeRet: {
    var elapsed_553648274 = ((timestamp_p0 - prevTimestamp_553648142[0]) / 1000.0);
    if ((elapsed_553648274 <= 0.06666666666666667)) {
    Temporary1 = update__main_u144.bind(this); Temporary1.ClP_0 = update__main_u144; Temporary1.ClE_0 = this;
    (window.requestAnimationFrame(Temporary1));
    break BeforeRet;
    }
    
    prevTimestamp_553648142[0] = timestamp_p0;
    outputBoard__main_u126(this.ctx0);
    mainloop__main_u142(this.ctx0);
    Temporary2 = update__main_u144.bind(this); Temporary2.ClP_0 = update__main_u144; Temporary2.ClE_0 = this;
    (window.requestAnimationFrame(Temporary2));
  };

  
}

function main__main_u138(event_p0) {
    var Temporary1;

    var HEX3Aenv_553648372 = null;
    HEX3Aenv_553648372 = {m_type: NTI553648336, ctx0: null};
    var canvas_553648268 = document.getElementById("canvas");
    canvas_553648268.width = 250;
    canvas_553648268.height = 250;
    HEX3Aenv_553648372.ctx0 = canvas_553648268.getContext("2d");
    randomize__pureZrandom_u299();
    shuffleBoard__main_u15();
    Temporary1 = update__main_u144.bind(HEX3Aenv_553648372); Temporary1.ClP_0 = update__main_u144; Temporary1.ClE_0 = HEX3Aenv_553648372;
    Temporary1(0.0);

  
}
var Temporary2;
var board_553648141 = [arrayConstr(52, new Int8Array(52), NTI553648147)];
var prevTimestamp_553648142 = [0.0];
Temporary2 = main__main_u138.bind(null); Temporary2.ClP_0 = main__main_u138; Temporary2.ClE_0 = null;
window.onload = Temporary2;
